MODEL_NAME: "GAN_GRU"
# MODEL_PATH: "/saved_models/GAN_GRU/gan_gru.pth"

data:
  context_size: 8
  horizon_size: 12
  num_entities: 11
  input_dim: 4
  output_dim: 2

model:
  state_dim_GNN: 32
  state_dim_RNN: 64
  state_dim_MLP: 32
  num_nodes: 64
  graph_conn_radius: 0.5


training:
  batch_size: 64
  epochs: 40
  lr: 0.001
  weight_decay: 0.0005
  scheduler_step_size: 300
  scheduler_gamma: 0.5
  grad_clip: 10.0
  seed: 0
  device: cuda

wandb:
  enabled: true
  mode: offline

optimization: # optimization ranges
  lr:
    type: float
    low: 0.0001
    high: 0.01
    log: true
    section: training
  weight_decay:
    type: float
    low: 0.00001
    high: 0.001
    log: true
    section: training
  batch_size:
    type: int
    low: 32
    high: 128
    section: training
  state_dim_GNN:
    type: int
    low: 16
    high: 64
    section: model
  state_dim_RNN:
    type: int
    low: 32
    high: 128
    section: model
  state_dim_MLP:
    type: int
    low: 32
    high: 128
    section: model
  num_nodes:
    type: int
    low: 32
    high: 128
    section: model
  graph_conn_radius:
    type: float
    low: 0.1
    high: 1.0
    section: model



  