MODEL_NAME: "HeteroSTGCN"
# MODEL_PATH: "/saved_models/stgcn_model/stgcn_model.pth"

data:
  context_size: 8
  horizon_size: 12
  num_entities: 11
  input_dim: 4
  output_dim: 2

model:
  state_dim: 64
  num_relations: 5

training:
  batch_size: 64
  epochs: 10
  lr: 0.001
  weight_decay: 0.0005
  scheduler_step_size: 300
  scheduler_gamma: 0.5
  grad_clip: 10.0
  seed: 0
  device: mps

wandb:
  enabled: true
  mode: offline

  