MODEL_NAME: "SpaceTimeGNN"

data:
  context_size: 8
  horizon_size: 12
  num_entities: 11
  input_dim: 4
  output_dim: 2

spacetime_graph:
  temporal_connexions: self_basic # Connect entity to itself at previous and next time step

model:
  num_relations: 7
  hidden_dim: 128
  dim_per_head: 32
  heads: 4
  num_layers: 2
  pred_head_hidden_dim: 64
  num_layers: 2 # Msg passing rounds

training:
  batch_size: 64
  epochs: 20
  lr: 0.001
  weight_decay: 0.0005
  scheduler_step_size: 300
  scheduler_gamma: 0.5
  grad_clip: 10.0
  seed: 0
  device: cuda
  early_stopping_patience: 5
  early_stopping_delta: 0.0001

wandb:
  enabled: true
  mode: offline